version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    ports:
    - 3000:3000
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
    - 1880:1880

    