version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    ports:
    - 3000:3000
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    expose:
    - 1883
    - 9001
    volumes:
      - ./mqtt/config:/mosquitto/config
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
    - 1880:1880
